import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * mcp-utils 2.9.0's credential healthcheck recognises an edge's refusal page,
 * but only from what the thrown error carries: its message, a
 * `body`/`bodyPreview`/`responseBody` string, headers, and `status`. These run
 * the REAL client against CloudFront's block page, so they fail if `request`
 * drops the body before the healthcheck can read it.
 */

const mintTokenViaFetchproxy = vi.fn();
vi.mock('../src/auth-fetchproxy.js', () => ({ mintTokenViaFetchproxy }));

const { ResyClient } = await import('../src/client.js');
const { registerHealthcheckTools } = await import('../src/tools/healthcheck.js');
const { EdgeBlockedError } = await import('@chrischall/mcp-utils');

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return {
    ok: false,
    status: 403,
    statusText: 'Forbidden',
    headers: new Headers({
      'content-type': 'text/html',
      'x-cache': 'Error from cloudfront',
      server: 'CloudFront',
    }),
    text: async () => CLOUDFRONT_BLOCK,
  } as unknown as Response;
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

async function healthcheck(client: InstanceType<typeof ResyClient>): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'resy_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    mintTokenViaFetchproxy.mockReset();
    process.env.RESY_AUTH_TOKEN = 'test-token';
    process.env.RESY_DISABLE_FETCHPROXY = '1';
    delete process.env.RESY_EMAIL;
    delete process.env.RESY_PASSWORD;
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    delete process.env.RESY_AUTH_TOKEN;
    delete process.env.RESY_DISABLE_FETCHPROXY;
  });

  it('on the /2/user probe', async () => {
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ResyClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/rejected the minted token/);
  });

  it('on the password login the probe triggers', async () => {
    delete process.env.RESY_AUTH_TOKEN;
    process.env.RESY_EMAIL = 'test@example.com';
    process.env.RESY_PASSWORD = 'pw';
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ResyClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/rejected the minted token/);
  });

  it('control: a 419 from Resy is still a rejected credential', async () => {
    fetchMock.mockResolvedValue({
      ok: false,
      status: 419,
      statusText: 'Unauthorized',
      headers: new Headers({ 'content-type': 'application/json' }),
      text: async () => JSON.stringify({ message: 'Unauthorized' }),
    } as unknown as Response);

    const r = await healthcheck(new ResyClient());

    expect(r.error?.kind).toBe('credential_rejected');
  });

  it('a blocked request throws EdgeBlockedError naming the vendor, never the whole page', async () => {
    fetchMock.mockResolvedValue(blocked());

    const err = await new ResyClient().request('GET', '/2/user').catch((e: unknown) => e);

    expect(err).toBeInstanceOf(EdgeBlockedError);
    const e = err as InstanceType<typeof EdgeBlockedError>;
    expect(e.status).toBe(403);
    expect(e.vendor).toBe('CloudFront');
    expect(e.message).toMatch(/GET \/2\/user/);
    expect(e.message).not.toMatch(/Request ID/);
  });
});

/**
 * A block page served with a 401 (or one only its BODY identifies) used to slip
 * past TokenManager's own block check: `request` reads the body inside the
 * withAuth callback, so the Response withAuth inspects has nothing left to
 * read. It then spent a re-mint (a real password login, or a bridge round
 * trip) and reported `credential_rejected`. The block must be recognised where
 * the body is still in hand.
 */
describe('a 401 block page never spends a re-mint (chrischall/mcp-host#1015)', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  // Body-only: no x-cache / server / cf-mitigated header says "CloudFront".
  function blocked401(): Response {
    return {
      ok: false,
      status: 401,
      statusText: 'Unauthorized',
      headers: new Headers({ 'content-type': 'text/html' }),
      text: async () => CLOUDFRONT_BLOCK,
    } as unknown as Response;
  }
  const login = (): Response =>
    ({
      ok: true,
      status: 200,
      statusText: 'OK',
      headers: new Headers({ 'content-type': 'application/json' }),
      text: async () => JSON.stringify({ token: 'minted' }),
    }) as unknown as Response;
  const logins = (): number =>
    fetchMock.mock.calls.filter(([url]) => String(url).endsWith('/3/auth/password')).length;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    delete process.env.RESY_AUTH_TOKEN;
    process.env.RESY_EMAIL = 'test@example.com';
    process.env.RESY_PASSWORD = 'pw';
    process.env.RESY_DISABLE_FETCHPROXY = '1';
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    delete process.env.RESY_EMAIL;
    delete process.env.RESY_PASSWORD;
    delete process.env.RESY_DISABLE_FETCHPROXY;
  });

  it('throws EdgeBlockedError after ONE login, with no re-mint or replay', async () => {
    fetchMock.mockImplementation(async (url: string) =>
      String(url).endsWith('/3/auth/password') ? login() : blocked401()
    );

    const err = await new ResyClient().request('GET', '/2/user').catch((e: unknown) => e);

    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as InstanceType<typeof EdgeBlockedError>).status).toBe(401);
    expect(logins()).toBe(1);
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it('the healthcheck reports edge_blocked, not credential_rejected', async () => {
    fetchMock.mockImplementation(async (url: string) =>
      String(url).endsWith('/3/auth/password') ? login() : blocked401()
    );

    const r = await healthcheck(new ResyClient());

    expect(r.error?.kind).toBe('edge_blocked');
    expect(logins()).toBe(1);
  });

  it('a block on the 429 backoff retry is EdgeBlockedError too', async () => {
    vi.useFakeTimers();
    try {
      let api = 0;
      fetchMock.mockImplementation(async (url: string) => {
        if (String(url).endsWith('/3/auth/password')) return login();
        api += 1;
        return api === 1
          ? ({
              ok: false,
              status: 429,
              statusText: 'Too Many Requests',
              headers: new Headers({ 'retry-after': '1' }),
              text: async () => '',
            } as unknown as Response)
          : blocked401();
      });

      const pending = new ResyClient().request('GET', '/2/user').catch((e: unknown) => e);
      await vi.runAllTimersAsync();
      const err = await pending;

      expect(err).toBeInstanceOf(EdgeBlockedError);
      expect(logins()).toBe(1);
    } finally {
      vi.useRealTimers();
    }
  });

  it('a block on the password login itself is EdgeBlockedError', async () => {
    fetchMock.mockImplementation(async () => blocked401());

    const err = await new ResyClient().request('GET', '/2/user').catch((e: unknown) => e);

    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  it('control: a genuine 401 from Resy still re-mints once and reads credential_rejected', async () => {
    fetchMock.mockImplementation(async (url: string) =>
      String(url).endsWith('/3/auth/password')
        ? login()
        : ({
            ok: false,
            status: 401,
            statusText: 'Unauthorized',
            headers: new Headers({ 'content-type': 'application/json' }),
            text: async () => JSON.stringify({ message: 'Unauthorized' }),
          } as unknown as Response)
    );

    const r = await healthcheck(new ResyClient());

    expect(r.error?.kind).toBe('credential_rejected');
    expect(logins()).toBe(2);
  });
});
