import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * mcp-utils 2.9.0's credential healthcheck recognises an edge's refusal page,
 * but only from what the thrown error carries: its message, a
 * `body`/`bodyPreview`/`responseBody` string, headers, and `status`. These run
 * the REAL client against CloudFront's block page, so they fail if `request`
 * drops the body before the healthcheck can read it.
 */

const mintTokenViaFetchproxy = vi.fn();
vi.mock('../src/auth-fetchproxy.js', () => ({ mintTokenViaFetchproxy }));

const { ResyClient } = await import('../src/client.js');
const { registerHealthcheckTools } = await import('../src/tools/healthcheck.js');

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return {
    ok: false,
    status: 403,
    statusText: 'Forbidden',
    headers: new Headers({
      'content-type': 'text/html',
      'x-cache': 'Error from cloudfront',
      server: 'CloudFront',
    }),
    text: async () => CLOUDFRONT_BLOCK,
  } as unknown as Response;
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

async function healthcheck(client: InstanceType<typeof ResyClient>): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'resy_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    mintTokenViaFetchproxy.mockReset();
    process.env.RESY_AUTH_TOKEN = 'test-token';
    process.env.RESY_DISABLE_FETCHPROXY = '1';
    delete process.env.RESY_EMAIL;
    delete process.env.RESY_PASSWORD;
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    delete process.env.RESY_AUTH_TOKEN;
    delete process.env.RESY_DISABLE_FETCHPROXY;
  });

  it('on the /2/user probe', async () => {
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ResyClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/rejected the minted token/);
  });

  it('on the password login the probe triggers', async () => {
    delete process.env.RESY_AUTH_TOKEN;
    process.env.RESY_EMAIL = 'test@example.com';
    process.env.RESY_PASSWORD = 'pw';
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ResyClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/rejected the minted token/);
  });

  it('control: a 419 from Resy is still a rejected credential', async () => {
    fetchMock.mockResolvedValue({
      ok: false,
      status: 419,
      statusText: 'Unauthorized',
      headers: new Headers({ 'content-type': 'application/json' }),
      text: async () => JSON.stringify({ message: 'Unauthorized' }),
    } as unknown as Response);

    const r = await healthcheck(new ResyClient());

    expect(r.error?.kind).toBe('credential_rejected');
  });

  it('the thrown error carries a bounded excerpt, never the whole page', async () => {
    fetchMock.mockResolvedValue(blocked());

    const err = (await new ResyClient().request('GET', '/2/user').catch((e: unknown) => e)) as {
      message: string;
      status?: number;
      bodyPreview?: string;
    };

    expect(err.message).toMatch(/Resy API error: 403 Forbidden for GET \/2\/user/);
    expect(err.status).toBe(403);
    expect(err.bodyPreview).toMatch(/The request could not be satisfied/);
    expect(err.bodyPreview!.length).toBeLessThan(CLOUDFRONT_BLOCK.length);
  });
});
